version: '3.8'

services:
  # Servicio de la aplicación web
  web:
    build: .
    image: portal-venta-diaria
    container_name: portal-venta-diaria
    restart: unless-stopped
    # Montamos el código fuente en /app
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    environment:
      # Flask environment
      FLASK_ENV: production
      # Service Layer de SAP B1
      SERVICE_LAYER_URL: https://hwvdvsbo04.virtualdv.cloud:50000/b1s/v1
      COMPANY_DB: PRDBERSA
      SL_USER: brsuser02
      # Si tu contraseña contiene un signo $, usa comillas simples para evitar interpretaciones
      SL_PASSWORD: '$PniBvQ7rBa6!A'
      # URL de la base de datos Neon (PostgreSQL)
      # Reemplaza los placeholders con tus credenciales reales
      DATABASE_URL: postgresql://<USUARIO>:<PASSWORD>@<HOST>:<PUERTO>/<DB_NAME>
      SECRET_KEY: <TU_SECRET_KEY>
    networks:
      - appnet
    command: >
      gunicorn --bind 0.0.0.0:5000 app:app

# El proxy reverso ha sido eliminado porque no se dispone de nginx.conf
# Si más adelante quieres añadir TLS o balanceo, podrías usar un contenedor nginx

networks:
  appnet:
    driver: bridge
